### ISSUE TITLE
申请 https 证书

### ISSUE THREAD

**Issue by happypeter** [happypeter/nrocks#3]
https://github.com/happypeter/onestep/issues/714

**Comment by happypeter** [comment]
@billie66

**Comment by billie66** [comment]
好的

**Comment by billie66** [comment]
已经申请了腾讯云免费的 TrustAsia SSL 证书，需要修改 nervos.org 域名的DNS配置，添加一条TXT记录

**Comment by happypeter** [comment]
nervos 那边已经在落实了

**Comment by billie66** [comment]
已经生效了
