### ISSUE TITLE
algolia 搜索

### ISSUE THREAD

**Issue by happypeter** [happypeter/nrocks#7]
https://community.algolia.com/docsearch/

达成跟 https://vuejs.org/ 类似的搜索体验

**Comment by billie66** [comment]
<img width="631" alt="screen shot 2018-09-28 at 8 33 16 pm" src="https://user-images.githubusercontent.com/102444/46208582-c9370080-c35d-11e8-9317-289ed259bd73.png">

**Comment by billie66** [comment]
algolia 发邮件说要确认是不是开源项目，需要提供GitHub代码仓库地址

**Comment by billie66** [comment]
algolia 搜索已经生效
